blueprint:
  name: Heating control
  description: "
  Controls the heater by the state of the window
  "
  domain: automation
  source_url: https://github.com/EinRainerZufall/ha-blueprints/blob/main/blueprints/automation/heating_control.yaml
  author: EinRainerZufall
  input:
    control_entity:
      name: Door or window
      description: The door or hte window to controll the heater
      selector:
        entity:
          filter:
            domain: binary_sensor
            device_class:
              - window
              - door
          multiple: true
    target_area:
      name: Heater
      description: The heater to be controled
      selector:
        target:
          entity:
            domain: climate

trigger:
  - platform: state
    entity_id: !input control_entity

action:
  if:
    - condition: state
      entity_id: !input control_entity
      state: "off"
  then:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: auto
      target: !input target_area
  else:
    - service: climate.set_hvac_mode
      data:
        hvac_mode: "off"
      target: !input target_area
